name: Docker Build & Push

on:
  push:
    branches:
      - multi-stage

jobs:
 docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-client:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-client:latest

      - name: Build & Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-server:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-server:latest
